# Generated by Django 2.1.1 on 2019-02-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publishDate',
        ),
    ]
